# 日志项配置
log:
  # 是否每次启动新建log文件
  force-new: false
  # 日志等级
  #   trace debug info warn error
  level: "debug"
  # 日志存活时间，到期新建log文件
  aging: 24h
  # 是否开启控制台颜色
  colorful: true

# http 验证密码
authorization:
  # 验证类型
  # - basic 进入网页输入密码 / 携带请求头验证
  # - authenticator 谷歌 2FA 验证
  type: 'basic'
  basic:
    # 密匙
    # 在网页直接输入 / 使用 Authorization 请求头进行验证
    secret: '123456'
  authenticator:
    xx: ''