# 日志项配置
log:
  # 是否每次启动新建log文件
  force-new: false
  # 日志等级
  #   trace debug info warn error
  level: "debug"
  # 日志存活时间，到期新建log文件
  aging: 24h
  # 是否开启控制台颜色
  colorful: true

# TODO
port:
  ssh: 10220
  http: 10221

# ip 白名单
whitelist: []

# 鉴权配置
authentication:
  # 鉴权类型
  # - token 固定 token 鉴权
  # - secret 使用 google-authenticator 生成的标准六位验证码鉴权
  # - pam /etc/pam.d/sshd 拦截，不启用转发
  type: ""
  # 鉴权 Token
  token: ""
  # base32-no-padding-encoded-string
  secret: ""